- name: Commit and push changes
  env:
    GH_TOKEN: ${{ secrets.GH_TOKEN }}
  run: |
    git config user.name "github-actions"
    git config user.email "github-actions@github.com"
    git add _posts
    git commit -m "🔄 Auto update posts" || echo "No changes to commit"
    git push https://x-access-token:${GH_TOKEN}@github.com/Darvish123/Gloun.git HEAD:main
